-- Migration: Create protein_cut table
-- Created: 2025-12-05

CREATE TABLE IF NOT EXISTS protein_cut (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cut_id INT NOT NULL,
    protein_id INT NOT NULL,
    price DECIMAL(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cut_id) REFERENCES cut(id) ON DELETE CASCADE,
    FOREIGN KEY (protein_id) REFERENCES protein(id) ON DELETE CASCADE
);
